application: guildlist
version: 3
runtime: python27
api_version: 1
threadsafe: true
module: default

handlers:
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest